# Confer docs/linting.md
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
  plugins:
    - custom_lint

custom_lint:
  enable_all_lint_rules: true
