name: ecostep
description: "Greenloop: A Platform for Recycling and Reusing through Sustainable Living"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.6
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  google_generative_ai: ^0.4.2
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  neopop: ^1.0.2
  random_string: ^2.3.1
  rive: ^0.13.5
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.1.0
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/rive_assets/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
