// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaSwCDrxnJZIPxzc18EuX18EkUsxamK0',
    appId: '1:145061817209:web:6daca8682521b2b5a65da8',
    messagingSenderId: '145061817209',
    projectId: 'greenloop-a67da',
    authDomain: 'greenloop-a67da.firebaseapp.com',
    storageBucket: 'greenloop-a67da.appspot.com',
    measurementId: 'G-GMPZXCB65F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtn-lHf_B2PPsdWlh_n7FUvIiDOeZq1Q',
    appId: '1:145061817209:android:ef4ec749d3f0c24aa65da8',
    messagingSenderId: '145061817209',
    projectId: 'greenloop-a67da',
    storageBucket: 'greenloop-a67da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv42MbPCnxuET_UoB9rXBF0zRZj_yb4yY',
    appId: '1:145061817209:ios:09dcab62fa99ed01a65da8',
    messagingSenderId: '145061817209',
    projectId: 'greenloop-a67da',
    storageBucket: 'greenloop-a67da.appspot.com',
    iosClientId: '145061817209-jb3r6pvmlbqlta9ja57h6ghemg7jk9jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecostep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv42MbPCnxuET_UoB9rXBF0zRZj_yb4yY',
    appId: '1:145061817209:ios:09dcab62fa99ed01a65da8',
    messagingSenderId: '145061817209',
    projectId: 'greenloop-a67da',
    storageBucket: 'greenloop-a67da.appspot.com',
    iosClientId: '145061817209-jb3r6pvmlbqlta9ja57h6ghemg7jk9jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecostep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRaSwCDrxnJZIPxzc18EuX18EkUsxamK0',
    appId: '1:145061817209:web:d010bdd28d2d6aada65da8',
    messagingSenderId: '145061817209',
    projectId: 'greenloop-a67da',
    authDomain: 'greenloop-a67da.firebaseapp.com',
    storageBucket: 'greenloop-a67da.appspot.com',
    measurementId: 'G-2795XFLMGT',
  );
}
